@startuml 雑イメージ
participant Client
participant Server
participant GameController


Server -> Server : Create Server

create GameController
Server -> GameController : new 

loop ２人揃うまで
     Server -> Server : accept
     Client -> Client : Create Client
     Client -> Server : TCPSocket.open
     
     Client -> Server : Join Request 
     Server -> GameController : Join Player Data
     Server --> Client : Join Responce
end

Server -> GameController : Get OrderData

GameController -> Server : Return OrderData

Server -> Client : OrderData

Client --> Client : Start Game

loop ゲーム終わるまで

    Server -> Client : TurnData

    Client -> Server : Play Request 
    Server --> Client : Play Responce 
    
    Server -> GameController : StonePosition
    GameController -> Server : BoardData
    Server -> Client : Board Data
end

' 終了

Server -> GameController : Get ResultData
GameController -> Server : Return ResultData


Server -> Client : ResultData

Client -> Client : Display Result

@enduml